baseurl = "https://joostmeijles.github.io/doc/"
languageCode = "en-us"
metadataformat = "yaml"
title = "My documentation page"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = ""

[params]
	name = ""
	description = ""

	github_user   = "joostmeijles"
	github_repo   = ""
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"

	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = false

[params.footer]
	copyright = "[Joost Meijles](http://joost.meijl.es)"
	show_powered_by = true